import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className=" bg-teal-700 text-white p-3 flex justify-between items-center">
          <Link href={"/"}>Home</Link>
          <ul className="flex  gap-4 items-center">
            <li>
              <Link href={"/posts"}>Posts</Link>
            </li>
            <li>
              <Link href={"/articles"}>Articles</Link>
            </li>
          </ul>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
